### ISSUE TITLE
Is it abandoned?

### ISSUE THREAD

**Issue by Olegt0rr** [aiokitchen/aiomisc-dependency#10]
It seems your library is abandoned.
[aiodine](https://github.com/bocadilloproject/aiodine) is abandoned too.

Only [python-dependency-injector](https://github.com/ets-labs/python-dependency-injector) is alive and supports actual python versions. 

So sad :( 
It would be nice to add in README shields with supported python versions.

**Comment by mosquito** [comment]
Nah, we are using it for our projects, when you have any problems just report.
